config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'blog', to: 'posts#index'
  resources :posts

  devise_for :users
  
  root 'pages#index'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :CategoryPost
  has_many :posts, through: :CategoryPost

  scope :featured, -> {where(:featured => true)}
end

app/models/category_post.rb
class CategoryPost < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/post.rb
class Post < ApplicationRecord
  before_save :unfeature_post, if: :featured?

  has_one_attached :thumbnail
  
  has_many :CategoryPost
  has_many :categories, through: :CategoryPost
  
  belongs_to :user

  private

  def unfeature_post
    featured_post = Post.find_by(featured: true)
    unless featured_post.nil?
      featured_post.update_column(:featured, false)
    end
  end
end

# It's not gonna work today haha so stop trying :-)
# No problemo
# i am getting angry, why?
# I am stupid, brain is not workign. why why why?
# Less sleep and coding for a few hours already, so you will reach a point your brain just don't work anymore
# Let me write down in plain english what's happening above

# Before saving a post, call unfeature_post if the post that's going to be saved is featured
# Find a post that already is featured
# unless that post is nill update that post and set featured to false
# r u there? now i am understanding, my brain is not working properly. 
# i cant even see those code properly, blury. yes, if you give me the permission, i want to leave. and go for bed.
# you are my GURU, so i need permission of you. ha ha ha.
# Talk to you tommmorrowo . 
# Byr
# yess haha maybe you should sleep
# haha why should i give you permission? If you want to sleep you should go man
# haha don't be so crazy man
# Have a good night and sleep well! chiao
# what? chiao???

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many  :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :is_admin?, only: [:edit, :destroy]
  def index
    @categories = Category.all
  end
  
  def new
    @category = Category.new
  end

  def create
    @category = Category.create(cat_params)
    if @category.save
      flash[:success] = "Category created successfully."
      redirect_to category_path(@category)
    else
      render 'new'
    end
  end

  def show
    @posts = @category.posts
  end
  
  def edit
  end

  def update
    if @category.update(cat_params)
      flash[:success] = "category updated successfully."
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end
  
  def destroy
    @category.destroy
    flash[:danger] = "Category deleted successfully."
    redirect_to categories_path
  end
  
  private
  def cat_params
    params.require(:category).permit(:name, :body, :featured)
  end
  
  def set_cat
    @category = Category.find(params[:id])
  end

  def is_admin?
    unless current_user.admin?
      flash[:danger] = "You are not authorized to perform this action!"
      redirect_to posts_path
    end
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @featured_categories = Category.featured
    @featured_post = Post.find_by(featured: true)
  end

  def about
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :required_post_user!, only: [:edit, :update, :destroy]

  def index
    @posts = Post.paginate(page: params[:page], per_page: 3).order('id DESC')
  end

  def new
    @post = Post.new
  end
  
  def create
    @post = Post.create(post_params)
    @post.user = current_user
    if @post.save
      flash[:success] = "Post created successfully"
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post updated successfully."
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
  end


  private
  def post_params
    params.require(:post).permit(:title, :content, :thumbnail, :featured, category_ids:[])
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def required_post_user!
    unless current_user.id == @post.user_id 
      redirect_to post_path(@post)
      flash[:danger] = "You are not authorized to perform this action!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, :html => {class: 'my-5 py-5'} do |f| %>
  <h3>Create New Category</h3>
  <div class="row">
    <div class="col-md-8">
      <div class="form-group row">
        <div class="col-md-12">
          <%= f.text_field :name, class: 'form-control', placeholder: 'Enter Category Title' %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-12">
          <%= f.trix_editor :body, placeholder: 'Category Details', rows: 10 %>
        </div>
      </div>
    </div>
    
    <div class="col-md-4">
      <div class="form-group row">
        <div class="col-sm-10">
          <div class="card mb-3">
            <div class="card-body">
              <div class="card-title mb-0">
                <p class="mb-0">Check the box if you want to show this categories post on front page.</p>
              </div>
            </div>
            <div class="card-footer">
              <div class="form-group form-check mb-0">
                <%= f.check_box :featured, class: 'form-check-input' %>
                <%= f.label :featured, class: 'form-check-label' %>
              </div>
            </div>
          </div>
          <div class="card">
            <div class="card-footer">
              <%= f.submit(@category.new_record? ? "Publish" : "Update", class: 'btn btn-outline-primary btn-sm') %>
              <% unless @category.new_record? %>
                <%= link_to "Cancle", category_path(@category), class: 'btn btn-outline-warning btn-sm' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= render "form" %>

app/views/categories/index.html.erb
<div class="row py-4">
  <div class="col-md-12">
    <div class="row mb-3">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <h2 class="float-left">All Categories</h2>
            <% if user_signed_in? %>
              <%= link_to  "Create New Category", new_category_path, class: 'btn btn-success btn-lg float-right' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <% @categories.each do |category| %>
      <div class="col-md-4">
        <div class="card mb-4">
          <div class="card-header">
            <h4 class="card-title"><%= category.name %></h4>
          </div>
          <div class="card-body">
              <p class="card-text"><%= truncate sanitize(category.body, tags: [], attributes: []), length: 50 %></p>
          </div>
          <div class="card-footer">
            <%= link_to  "View", category_path(category), class: 'card-link' %>
            <% if user_signed_in? && current_user.admin? %>
              <%= link_to  "Edit", edit_category_path(category), class: 'card-link' %>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<%= render "form" %>

app/views/categories/show.html.erb
<div class="row py-5">
  <div class="col-md-8 offset-md-2">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title"><%= @category.name %></h4>
        <p class="card-text"><%= sanitize(@category.body) %></p>
        
      </div>
      <div class="card-footer">
        <% if user_signed_in? && current_user.admin? %>
          <%= link_to  "Edit", edit_category_path(@category), class: 'btn btn-outline-primary btn-sm' %>
          <%= link_to  "Cancle", categories_path, class: 'btn btn-outline-warning btn-sm' %>
        <% else %>
          <%= link_to  "All Categories", categories_path, class: 'btn btn-outline-danger btn-sm' %>
        <% end %>
        <span class="btn btn-primary-outlined float-right">
          <%= pluralize(@posts.count, "post") %> Under <%= "#{@category.name}" %>
        </span>
      </div>
    </div>
  </div>
</div>

<% @posts.each do |catpost| %>
<div class="row pb-5">
  <div class="col-md-8 offset-md-2">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title"><%= link_to catpost.title, post_path(catpost) %></h4>
      </div>
      <div class="card-footer">
        <% if user_signed_in? && current_user.admin? %>
          <%= link_to  "Edit", edit_post_path(catpost), class: 'btn btn-outline-primary btn-sm' %>
          <%= link_to  "Cancle", categories_path, class: 'btn btn-outline-warning btn-sm' %>
        <% else %>
          <%= link_to  "All Categories", categories_path, class: 'btn btn-outline-danger btn-sm' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
<div class="row">
  <div class="col-md-8 offset-md-2">
    <div class="alert alert-<%= "#{name}" %> alert-dismissible fade show" role="alert">
      <strong><%= msg %></strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kids</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  
  <body>
    <%= render  "shared/navbar" %>
    <div class="container pt-5 mt-5">
      <%= render  "layouts/messages" %>
      
      <%= yield %>
    </div>
    
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/index.html.erb
<% unless @featured_post.nil? %>
<div class="jumbotron grbg1">
  <div class="container">
    <h1 class="display-3 heading"><%= @featured_post.title %></h1>
    <p class="mt-4"><%= truncate sanitize(@featured_post.content, tags: [], attributes: []), length: 200 %></p>
    <hr class="my-2">
    <p>
      <%= link_to  "Continue Reading", post_path(@featured_post), class: 'btn btn-outline-light' %>
    </p>
  </div>
</div>
<% end %>


<div class="row mb-5">
  <% @featured_categories.each do |fetcat| %>
  <div class="col-md-4">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title mb-0">
          <%= link_to fetcat.name, category_path(fetcat) %>
        </h4>
      </div>
      <ul class="list-group list-group-flush">
      <% fetcat.posts.last(3).each do |p| %>
        <li class="list-group-item">
          <%= link_to truncate(p.title, length: 40), post_path(p), class: 'text-muted' %>
        </li>
      <% end %>
      </ul>
      <div class="card-footer">
        <%= link_to  "View All Posts", category_path(fetcat), class: 'float-right text-muted' %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/posts/_form.html.erb
<%= form_for @post, :html => {class: 'my-5 py-3'} do |f| %>
  <h3>Create New Post</h3>
  <div class="row">
    <div class="col-md-8">
      <div class="form-group row">
        <div class="col-md-12">
          <%= f.text_field :title, class: 'form-control', placeholder: 'Enter Post Title' %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-12">
          <%= f.trix_editor :content, placeholder: 'Post Content', rows: 10 %>
        </div>
      </div>
    </div>
    
    <div class="col-md-4">
      <div class="form-group row">
        <div class="col-sm-10">
          <div class="card">
            <div class="card-footer">
              <%= f.submit(@post.new_record? ? "Publish" : "Update", class: 'btn btn-outline-primary btn-sm') %>
              <% unless @post.new_record? %>
                <%= link_to "Cancle", post_path(@post), class: 'btn btn-outline-warning btn-sm' %>
              <% end %>
            </div>
          </div>
          <div class="card mt-3">
            <div class="card-footer">
              <%= f.file_field :thumbnail %>
            </div>
          </div>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-10">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">All Categories</h3>
            </div>
            <div class="card-body">
              <div class="custom-control custom-checkbox pl-0">
                <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
                  <div>
                  <%= b.label(:"data-value" => b.value) { b.check_box + b.text } %>
                  </div>
                <% end %>
                <%# <input type="checkbox" class="custom-control-input" id="customControlInline">
                <label class="custom-control-label" for="customControlInline">Remember my preference</label> %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <% if current_user.admin %>
      <div class="form-group row">
        <div class="col-sm-10">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Featured</h3>
            </div>
            <div class="card-body">
              <div class="custom-control custom-checkbox">
                <%= f.check_box :featured, class: 'form-check-input' %>
                <%= f.label :featured, class: 'form-check-label' %>
                <%# <input type="checkbox" class="custom-control-input" id="customControlInline">
                <label class="custom-control-label" for="customControlInline">Remember my preference</label> %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= render  "form" %>

app/views/posts/index.html.erb
<div class="row py-4">
  <div class="col-md-10 offset-md-1">
    <% @posts.each do |post| %>
    <article class="bg-white mb-2">
      <div class="row">
        <div class="col-md-3">
          <% if post.thumbnail.attached? %>
            <%= image_tag post.thumbnail, class: 'card-img-top img-fluid' %>
          <% else %>
            <%= image_tag "image_not_available", class: 'card-img-top img-fluid' %>
          <% end %>
        </div>
        <div class="col-md-9">
          <div class="p-2">
            <header>
              <p class="h5 article_title font-weight-bold">
                <%= link_to post.title, post_path(post) %>
              </p>
            </header>
            <div class="content">
              <%= truncate sanitize(post.content, tags: [], attributes: []), length: 100 %>
            </div>
            <footer class="mt-3 small">
              <span class="text-muted">
                Published at - 
                <%= post.created_at.strftime('%b %e, %l:%M %p') %>
              </span>
              <span> | </span>
              <span class="text-muted">
                By - <%= post.user.email[/[^@]+/]  %>
              </span>
              <span> | </span>
              <span class="text-muted">
                On - 
                <% unless post.categories.blank? %>
                  <% post.categories.each do |catpost|  %>
                    <%= link_to catpost.name, catpost %>
                    <%= "," unless catpost == post.categories.last %>
                  <% end %>
                <% else %>
                  <%= "No Categories Available" %>
                <% end %>
              </span>
            </footer>
          </div>
        </div>
      </div>
    </article>
    <% end %>
    <%= will_paginate @posts, list_classes: %w(pagination justify-content-center mt-5) %>
  </div>
</div>

app/views/posts/new.html.erb
<%= render  "form" %>

app/views/posts/show.html.erb
<div class="row py-5">
  <div class="col-md-8 offset-md-2">
    <div class="card article">
      <% if @post.thumbnail.attached? %>
        <%= image_tag @post.thumbnail, class: 'card-img-top img-fluid' %>
      <% else %>
        <%= image_tag "1200x480.png", class: 'card-img-top img-fluid' %>
      <% end %>
      <div class="card-body">
        <h4 class="card-title"><%= @post.title %></h4>
        <p class="card-text"><%= sanitize (@post.content) %></p>
      </div>
      <% if user_signed_in? && current_user.id == @post.user_id %>
        <div class="card-footer">
          <%= link_to  "Edit", edit_post_path(@post), class: 'btn btn-outline-primary btn-sm' %>
          <%= link_to  "Cancle", posts_path, class: 'btn btn-outline-warning btn-sm' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="mainfooter grbg1">
  <div class="container">
    <div class="row text-center">
      <p class="mb-0 py-2 w-100">All right reserved, &copy 2019 by <a href="https://smehsan.com">smehsan</a></p>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-dark grbg1">
  <div class="container">
    <%= link_to  "Kids Zone", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <form class="form-inline my-2 my-lg-0 mr-auto w-50 d-flex justify-content-center">
        <input class="form-control mr-sm-2 w-75" type="text" placeholder="Search">
        <button class="btn btn-danger my-2 my-sm-0" type="submit">Search</button>
      </form>
      <ul class="navbar-nav mt-2 mt-lg-0">
        <li class="nav-item active">
          <%= link_to  "Blog", posts_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to  "Contact", contact_path, class: 'nav-link' %>
        </li>
        <% if !user_signed_in? %>
          <li class="nav-item active">
            <%= link_to  "Sign In", new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to  "Sign Up", new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Profile
          </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to  "All Categories", categories_path, class: 'dropdown-item' %>
              <% if user_signed_in? %>
                <%= link_to  "Sign Out", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
                <div class="dropdown-divider"></div>
                <%= link_to  "New Post", new_post_path, class: 'dropdown-item' %>
              <% end %>
            </div>
        </li>
      </ul>
    </div>
  </div>
</nav>